# Generated by Django 5.2.17 on 2026-09-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='business.employee'),
        ),
    ]
