# Generated by Django 5.2.17 on 2026-09-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_delivery_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
